### PR TITLE
Backport win,tty fixes for Windows systems

### PR DESCRIPTION
**Pull request by musm**
Backport several patches.
These changes help to enable and support  VT sequences on Windows.

### CODE REVIEW

**Comment by musm** [comment]
The last two commits are not necessary, but I think they can't  hurt to add. I'm happy  to remove them if desired.

**Comment by musm** [comment]
@vtjnash  What do think about this, Is this ok to merge  or do you have bigger concerns?   I'd like to also get in https://github.com/libuv/libuv/pull/2910 eventually when that get's merged upstream.

**Comment by StefanKarpinski** [comment]
Would be great to get this merged.

**Comment by musm** [comment]
merging in a few days sans objections

**Comment by vtjnash** [comment]
It looks like I previously either authored or reviewed each of these, so I guess I'm on board.

**Comment by musm** [comment]
merge commit / squash and merge / rebase and merge?


I'm guessing rebase and merge?

**Comment by vtjnash** [comment]
That'd be fine, and probably clearest in the history log

**Comment by c42f** [comment]
Fantastic, thanks @musm. I've hit many problems with VT support on windows which really can't be worked around.  I think this will sort them out.

**Pull request merged**
