### PR TITLE
Changes to support color VT sequences on windows

### PR DESCRIPTION
**Pull request by musm**

### CODE REVIEW

**Comment by musm** [comment]
@vtjnash  I don't understand your concern for https://github.com/JuliaLang/julia/issues/27782 

Executing `shell> cmd /C dir` works fine with this patch and remove the codepage setting in libsupport.c in julia

**Comment by vtjnash** [comment]
Yes, see the linked issues: they are for many exe's that _aren't_ `cmd`.

**Comment by davidanthoff** [comment]
How can one reproduce https://github.com/JuliaLang/julia/issues/26894 or https://github.com/JuliaLang/julia/issues/27782? I used the binary that @musm provided [here](https://www.dropbox.com/s/w4zr2tkldz15f12/julia-a62b8ec9c6-win64.exe?dl=0) that includes all his libuv and julia patches, and then I tried the following things, none of which show a problem:

1. I start julia from the start menu, and press `;ls`. That actually doesn't work, because of course `ls` is not around...
2. I start git bash, inside git bash I start julia, and then type `;ls`. Everything looks good. Same for `;pwd`.
3. I start julia from the start menu, and run `;python`. Everything works.
4. I start julia from the start menu, and run `;powershell`. Everything works.

CCing @KristofferC, given that he originally reported https://github.com/JuliaLang/julia/issues/26894. Any suggestion how we might be able to trigger that?

**Comment by KristofferC** [comment]
Try https://github.com/JuliaLang/julia/issues/26894#issuecomment-383901827 perhaps.

**Comment by davidanthoff** [comment]
Yes, now I can reproduce that, thanks!

So, just to record that here, the repo is as follows:
1. Start the julia binary that @musm provided
2. In the shell mode, run from the git folder `echo blob`

Does this only happen for the stuff from Git, or are there any other command line programs that have the same issue?

Here is one clue what is wrong here: when I call `GetConsoleMode` _before_ I run the shell command, the `ENABLE_VIRTUAL_TERMINAL_PROCESSING` flag is set. If I run it afterwards (from the corrupted prompt), it is no longer set. So that probably explains why things no longer work: somehow the console is now configured to not interpret VT sequences anymore.

So I guess the real question is how can that happen? Presumably what is happening is that `echo.exe` is changing the configuration for the console output handle to remove that flag. And this flag is probably per console, not per process, right?

If so, the solution would probably be to do the following whenever a child process is started:
1. check whether `ENABLE_VIRTUAL_TERMINAL_PROCESSING` is set
2. run the child process
3. set `ENABLE_VIRTUAL_TERMINAL_PROCESSING` again if it was unset by the child process in the meantime

**Comment by davidanthoff** [comment]
There are probably other console specific configurations that a child process in theory could also change and cause trouble? So maybe the right thing to do would be to just call `GetConsoleMode` before one runs an external program, store all of that, run the external program, and then `SetConsoleMode` with all the settings that one had obtained previously?

**Comment by musm** [comment]
Is this then isolated to  down to `jl_spawn`  which ends up calling `uv_spawn`. So again, needs to resolved in libuv?

**Comment by musm** [comment]
@davidanthoff can you explain again how you reproduced the issue? Are you able to trigger the issue only from git-bash ?  I'm unable to trigger the issue from julia within cmd.  But  running julia from a git bash prompt or running the julia.exe from within wsl I can trigger the issue.

**Comment by davidanthoff** [comment]
I installed your compiled version of julia 1.2.0-DEV, then opened the folder where it is installed and double clicked on the julia.exe in there. Then I did this:

image

That reproduces the issue for me.

I then copy-pasted the code that calls `GetConsoleMode` into that corrupted console, and it shows that the flag is no longer set after I ran the external `echo.exe`.

**Comment by musm** [comment]
@vtjnash  Do you think we need to reset the console state in `jl_spawn` after the `uv_spawn` call?  Or is the solution, related to fixing some of the callbacks in  libuv  in `process.jl` to check the term state...

**Comment by musm** [comment]
@vtjnash  I updated the branch here by pulling in  PR https://github.com/libuv/libuv/pull/2129

It seems   we need to set `uv_tty_set_vterm_state(handle, UV_TTY_AUTODETECT);` somewhere in `process.c` .  This is what  @davidanthoff is suggesting or his theory of what it is occuring: i.e. the client process changes the console mode.  

I'm not sure if we need to handle anything in the julia side with regards to `jl_spawn`. 

Any input would be appreciated.

**Comment by musm** [comment]
Indeed, it seems that David is correct here

https://stackoverflow.com/questions/52607960/how-can-i-enable-virtual-terminal-processing

> The mode setting gets set for the console (i.e. conhost.exe), not the calling process. Specifically it's set for the active console sreen buffer that the process inherited as its StandardOutput. The issue is actually that the parent process is saving the current console mode settings before executing the child and then resets the mode after the child exits. The CMD shell, for example, has worked like this since it was ported as a Windows console application in the early 1990s. In particular, CMD runs programs using the original mode it saved at startup

**Comment by musm** [comment]
One thing that I am curious about is if this only occurs in the `shell>` state .

If this is true   julia needs to reset the terminal state after we exit the `shell>` repl state. In other words, I'm not sure that there is anything wrong with the spawn process, but rather the julia terminal failing to reset after switching back to julia repl.

**Comment by musm** [comment]
Based on the previous comment, the following commit  resets the terminal state  after every shell command
https://github.com/musm/julia/commit/2feac0bda497e877c69f4fb455b48b761d28d56c

which does fix the issue that the julia repl gets a corrupted consolemode after spawning certain executables

@vtjnash  is this a sufficient patch in julia to resolve the bug you brought to attention?

Test installers (this pr + julia patch shown above): https://www.dropbox.com/s/sutliotmvb9l8k8/julia-6740f8784b-win64.exe?dl=0


EDIT:  That doesn't work, since it corrupted the shell mode in a different way...

**Comment by StefanKarpinski** [comment]
@musm, can you please leave PRs like this open even if they don't get merged right away? Sometimes it takes a while to get things reviewed and merged.

**Comment by musm** [comment]
@StefanKarpinski I closed this since it's stale.  The main reason is this branch needs  to be updated to the latest libuv branch we are using  `julia-uv2-1.29.1`, which is a trivial change, but it requires  a new PR.

**Comment by StefanKarpinski** [comment]
It's also possible to rebase the existing PR; keeping it open acts as a way of keeping track of the PR since closed PRs are generally never looked at again, whereas open PRs will be looked at.

**Comment by musm** [comment]
Can't we just agree that the problem is not this PR, but the broken repl shell mode in julia?  

I would be in favor of merging this PR. And either trying to fix the broken repl shell mode rather than holding up this useful PR, that is much more practically relevant. 

The examples that break the repl shell mode are quite esoteric as evidence by what one has to do to trigger it.

**Comment by musm** [comment]
Neither my hacking nor @davidanthoff  have been able to successfully resolve the shell mode bug. And seeing that  no one else has tried to resolve the issue, I think it should be appropriate to merge this PR in some form.

**Comment by musm** [comment]
I would love some feedback, before trying to rebase this based on my previous comments.

**Comment by musm** [comment]
Superseded by https://github.com/JuliaLang/libuv/pull/11 which is opened against the latest julia libuv fork 

(In other words, this is stale since it's opened against an old fork)

**Pull request closed without merging**
