### PR TITLE
add ppc cpuid fix

### PR DESCRIPTION
**Pull request by shirodkara**
add PPC CPU detection fix

### CODE REVIEW

**Comment by vchuravy** [comment]
@vtjnash what do we need to do carry this for Julia base?

**Comment by vtjnash** [comment]
Seems to be a backport of:
```
commit b12699b1efabfd241324f4ab6cfd6ce576db491e
Author: Richard Lau <rlau@redhat.com>
Date:   Wed Jul 7 21:19:47 2021 +0100

    linux: read CPU model information on ppc
    
    Fixes: https://github.com/libuv/libuv/issues/3217
    PR-URL: https://github.com/libuv/libuv/pull/3232
    Reviewed-By: Jameson Nash <vtjnash@gmail.com>
```
so this is okay, or it can wait for me to make a release this week upstream (which included that commit)

**Comment by vchuravy** [comment]
> so this is okay, or it can wait for me to make a release this week upstream (which included that commit) 

As long as we pick it up in your next bump :)

**Comment by shirodkara** [comment]
@vtjnash yes its the same backport, i guess its fine if it comes in the next weekly upstream that has the commit . 

Thanks

**Pull request closed without merging**
